import json
import os
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.set_page_config(page_title="ImpactLens v2", layout="wide")

st.title("ImpactLens v2 — Contribution as System Impact (Demo)")

colA, colB = st.columns([2,1])
with colA:
    st.caption("Load output.json generated by the backend pipeline.")
with colB:
    st.caption("No leaderboards. Role + band + explainability.")

default_path = "output.json"
path = st.text_input("Path to output.json", value=default_path)

if not os.path.exists(path):
    st.warning("Run backend first to generate output.json.")
    st.stop()

with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

meta = data.get("meta", {})
st.write("**Run mode:**", meta.get("mode"), "| **Concurrency:**", meta.get("concurrency_score"), "| **Dep density:**", meta.get("dependency_density"))

results = pd.DataFrame(data["results"])

# --- Team overview ---
st.subheader("Team Overview")
c1, c2, c3 = st.columns(3)

with c1:
    st.metric("Members", len(results))

with c2:
    band_counts = results["band"].value_counts()
    fig = plt.figure()
    plt.title("Band distribution")
    plt.bar(band_counts.index, band_counts.values)
    plt.xticks(rotation=45, ha="right")
    st.pyplot(fig)

with c3:
    # primary roles
    primary_roles = results["roles"].apply(lambda rs: rs[0]["name"] if rs else "Unknown")
    role_counts = primary_roles.value_counts()
    fig = plt.figure()
    plt.title("Primary role distribution")
    plt.bar(role_counts.index, role_counts.values)
    plt.xticks(rotation=45, ha="right")
    st.pyplot(fig)

st.divider()

# --- Per-person view ---
st.subheader("Individual View")
person = st.selectbox("Select a person", results["name"].tolist())

row = results[results["name"] == person].iloc[0]

left, right = st.columns([2, 1])

with left:
    st.markdown(f"### {row['name']}")
    st.write("**Band:**", row["band"])
    st.write("**Score:**", row["score"])

    roles = row["roles"]
    st.write("**Roles (Top-2):**")
    for r in roles:
        st.write(f"- {r['name']} (confidence {round(r['confidence'], 2)})")

    st.write("**Trend:**", row["trend"])

with right:
    st.write("**Integrity**")
    st.write("Penalty:", row["integrity"]["penalty"])
    st.write("Flags:", ", ".join(row["integrity"]["flags"]) if row["integrity"]["flags"] else "None")

    st.write("**Evidence**")
    st.write("Peer-validated claims:", row["evidence"]["peer_validated_claims"])
    st.write("Invisible score:", row["evidence"]["invisible_score"])

st.divider()

st.subheader("Explainability")
pos = row["explanations"]["top_positive"]
neg = row["explanations"]["top_negative"]
col1, col2 = st.columns(2)
with col1:
    st.write("**Top positive drivers**")
    for x in pos:
        st.write("- ", x)
with col2:
    st.write("**Top negative drivers**")
    if not neg:
        st.write("- None")
    else:
        for x in neg:
            st.write("- ", x)

st.subheader("Recourse / What to improve (MVP)")
# simple recourse already embedded in explanations/flags; for now show guardrails + advice
st.write("**Guardrails**")
for g in row["guardrails"]:
    st.write("- ", g)

st.info("Tip: Switch dataset by rerunning backend with a different demo scenario folder.")
